const normalizeSlug = (value) => {
  const slug = value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
  const safeSlug = slug || 'M4L_Remote_Mapper'
  return /^\d/.test(safeSlug) ? `M4L_${safeSlug}` : safeSlug
}

const pyString = (value) => JSON.stringify(String(value))

export const createScriptSlug = (deviceName) => `${normalizeSlug(deviceName)}_Remote`

export function generateParameterNames({ parameterCount, parameterPrefix }) {
  return Array.from(
    { length: Math.max(1, Number(parameterCount) || 1) },
    (_, index) => `${parameterPrefix || 'M4L Param'} ${index + 1}`,
  )
}

export function generateButtonNames({ buttonCount = 8, buttonPrefix = 'M4L Button' }) {
  return Array.from(
    { length: Math.max(1, Number(buttonCount) || 1) },
    (_, index) => `${buttonPrefix || 'M4L Button'} ${index + 1}`,
  )
}

function buildPythonMappings(mappings) {
  const rows = mappings.map((mapping) => {
    const source = mapping.source
    if (mapping.targetType === 'global_action') {
      return `        {"channel": ${source.frameworkChannel}, "cc": ${source.data1}, "control_type": "button", "type": "global_action", "action": ${pyString(mapping.actionName)}, "button_mode": ${pyString(mapping.buttonMode || 'trigger')}, "trigger": ${pyString(mapping.triggerMode)}}`
    }
    if (mapping.targetType === 'm4l_button') {
      return `        {"channel": ${source.frameworkChannel}, "cc": ${source.data1}, "control_type": "button", "type": "m4l_button", "device": ${pyString(mapping.targetDeviceName)}, "parameter": ${pyString(mapping.targetButtonName)}, "button_mode": ${pyString(mapping.buttonMode || 'momentary')}, "button_id": ${pyString(`${source.frameworkChannel}:${source.data1}`)}, "parameter_index": None}`
    }
    const parameterIndex = mapping.parameterIndex === '' || mapping.parameterIndex == null
      ? 'None'
      : Number(mapping.parameterIndex)
    return `        {"channel": ${source.frameworkChannel}, "cc": ${source.data1}, "control_type": "continuous", "type": "m4l_parameter", "device": ${pyString(mapping.targetDeviceName)}, "parameter": ${pyString(mapping.targetParameterName)}, "scaling": "parameter_min_max", "parameter_index": ${parameterIndex}}`
  })
  return rows.length ? `${rows.join(',\n')}\n` : ''
}

export function generateRemoteScriptFiles({ target, mappings, scriptSlug = createScriptSlug(target.targetDeviceName) }) {
  const profile = {
    schemaVersion: '0.1',
    scriptSlug,
    target,
    mappings: mappings.map((mapping) => ({
      source: mapping.source,
      controlType: mapping.controlType || (mapping.targetType === 'm4l_parameter' ? 'continuous' : 'button'),
      targetType: mapping.targetType,
      ...(mapping.targetType === 'global_action'
        ? {
            actionName: mapping.actionName,
            buttonMode: mapping.buttonMode || 'trigger',
            triggerMode: mapping.triggerMode,
          }
        : mapping.targetType === 'm4l_button'
          ? {
              targetDeviceName: mapping.targetDeviceName,
              targetButtonName: mapping.targetButtonName,
              buttonMode: mapping.buttonMode || 'momentary',
            }
          : {
            targetDeviceName: mapping.targetDeviceName,
            targetParameterName: mapping.targetParameterName,
            scaling: mapping.scaling || 'parameter_min_max',
            parameterIndex: mapping.parameterIndex === '' ? null : mapping.parameterIndex,
          }),
    })),
  }

  const initPy = `from .${scriptSlug} import ${scriptSlug}\n\n\ndef create_instance(c_instance):\n    return ${scriptSlug}(c_instance)\n`

  const scriptPy = `# Generated by M4L Remote Mapper v0.1
import Live
from _Framework.ControlSurface import ControlSurface
from _Framework.InputControlElement import MIDI_CC_TYPE
from _Framework.EncoderElement import EncoderElement


class ${scriptSlug}(ControlSurface):
    MAPPINGS = [
${buildPythonMappings(mappings)}    ]

    def __init__(self, c_instance):
        super(${scriptSlug}, self).__init__(c_instance)
        with self.component_guard():
            self._log("M4L Remote Mapper: script loaded")
            self._setup_mappings()

    def _log(self, message):
        try:
            self.canonical_parent.log_message(message)
        except Exception:
            try:
                self.show_message(message)
            except Exception:
                pass

    def _setup_mappings(self):
        self._mappings = list(self.MAPPINGS)
        self._controls = []
        self._button_states = {}
        for mapping in self._mappings:
            control = EncoderElement(
                MIDI_CC_TYPE,
                mapping["channel"],
                mapping["cc"],
                Live.MidiMap.MapMode.absolute
            )
            control.add_value_listener(self._make_value_listener(mapping))
            self._controls.append(control)
            self._log("listening CC channel={} cc={}".format(mapping["channel"], mapping["cc"]))

    def _make_value_listener(self, mapping):
        def listener(value):
            self._log("CC received channel={} cc={} value={}".format(mapping["channel"], mapping["cc"], value))
            self._apply_mapping(mapping, value)
        return listener

    def _apply_mapping(self, mapping, value):
        if mapping["type"] == "global_action":
            self._run_global_action(mapping, value)
            return
        parameter = self._find_parameter(mapping)
        if parameter is None:
            return
        if mapping["type"] == "m4l_button":
            self._apply_button_mapping(mapping, value, parameter)
            return
        scaled_value = self._scale_midi_to_parameter(value, parameter)
        parameter.value = scaled_value
        self._log("parameter updated: {} value={} scaled={}".format(parameter.name, value, scaled_value))

    def _apply_button_mapping(self, mapping, value, parameter):
        button_mode = mapping.get("button_mode", "momentary")
        if button_mode in ("momentary", "toggle_from_input"):
            parameter.value = parameter.max if value > 0 else parameter.min
            self._log("button updated: {} mode={} value={}".format(parameter.name, button_mode, value))
            return
        if button_mode == "toggle_in_script":
            if value != 127:
                return
            button_id = mapping.get("button_id", "{}:{}".format(mapping["channel"], mapping["cc"]))
            state = not self._button_states.get(button_id, False)
            self._button_states[button_id] = state
            parameter.value = parameter.max if state else parameter.min
            self._log("button toggled: {} state={}".format(parameter.name, state))
            return
        if button_mode == "trigger":
            if value != 127:
                return
            parameter.value = parameter.max
            parameter.value = parameter.min
            self._log("button triggered: {}".format(parameter.name))

    def _scale_midi_to_parameter(self, midi_value, parameter):
        try:
            minimum = float(parameter.min)
            maximum = float(parameter.max)
            normalized = max(0.0, min(1.0, float(midi_value) / 127.0))
            return minimum + ((maximum - minimum) * normalized)
        except Exception:
            return max(0.0, min(1.0, float(midi_value) / 127.0))

    def _run_global_action(self, mapping, value):
        if mapping["action"] != "Capture MIDI":
            return
        if mapping["trigger"] != "value_eq_127":
            return
        if value == 127:
            self._log("M4L Remote Mapper: global action requested: Capture MIDI")
            self._log("M4L Remote Mapper: capture_midi requested")
            try:
                self.song().capture_midi()
                self._log("M4L Remote Mapper: capture_midi success")
            except Exception as error:
                self._log("M4L Remote Mapper: capture_midi error: %s" % error)

    def _find_parameter(self, mapping):
        target_device = None
        for track in list(self.song().tracks) + list(self.song().return_tracks):
            target_device = self._find_device_in_chain(track.devices, mapping["device"])
            if target_device is not None:
                break
        if target_device is None:
            self._log("target device missing: {}".format(mapping["device"]))
            return None
        self._log("target device found: {}".format(mapping["device"]))

        exact_name = mapping["parameter"]
        for parameter in target_device.parameters:
            if parameter.name == exact_name:
                self._log("parameter found: {}".format(exact_name))
                return parameter

        normalized_name = self._normalize_name(exact_name)
        for parameter in target_device.parameters:
            if self._normalize_name(parameter.name) == normalized_name:
                self._log("parameter found: {}".format(exact_name))
                return parameter

        automatable_parameters = [parameter for parameter in target_device.parameters if parameter.name != "Device On"]
        index = mapping.get("parameter_index")
        if index is not None and 0 <= index < len(automatable_parameters):
            self._log("parameter found: {}".format(exact_name))
            return automatable_parameters[index]
        self._log("parameter missing: {}".format(exact_name))
        return None

    def _find_device_in_chain(self, devices, target_name):
        normalized_target = self._normalize_name(target_name)
        for device in devices:
            if device.name == target_name or self._normalize_name(device.name) == normalized_target:
                return device
            if getattr(device, "can_have_chains", False):
                for chain in device.chains:
                    nested = self._find_device_in_chain(chain.devices, target_name)
                    if nested is not None:
                        return nested
        return None

    @staticmethod
    def _normalize_name(value):
        return "".join(character.lower() for character in value if character.isalnum())
`

  const readme = `# ${target.targetDeviceName} Remote Pack

Generated by M4L Remote Mapper. This pack connects MIDI CC messages to named Max for Live parameters and Ableton global actions.

## Profile

- Target device: **${target.targetDeviceName}**
- Parameters: **${target.parameterCount}**
- Buttons: **${target.buttonCount || 8}**
- Active mappings: **${mappings.length}**
- Remote Script folder: \`${scriptSlug}\`

See \`3_READ_ME_FIRST.md\` for setup instructions. The ready-to-open Max patch is in \`2_OPEN_THIS_MAX_FOR_LIVE_DEVICE/M4L-Remote-Target/\`.
`

  const installation = `# Installation

1. Quit Ableton Live.
2. Copy only \`1_COPY_THIS_FOLDER_TO_REMOTE_SCRIPTS/${scriptSlug}\` into Ableton's User Remote Scripts folder.
   - macOS: \`~/Music/Ableton/User Library/Remote Scripts/\`
   - Windows: \`%USERPROFILE%\\Documents\\Ableton\\User Library\\Remote Scripts\\\`
3. Open \`2_OPEN_THIS_MAX_FOR_LIVE_DEVICE/M4L-Remote-Target/M4L-Remote-Target.maxpat\` in Max for Live and save the device under the exact name **M4L-Remote-Target** if necessary.
4. Restart Live and open **Settings → Link, Tempo & MIDI**.
5. Select **${scriptSlug}** as Control Surface, **nanoKONTROL2 SLIDER/KNOB** as Input, and **None** as Output.
6. Add the Max for Live device named **${target.targetDeviceName}** to a track.
7. Move a mapped control and verify the parameter response.

If nothing moves, verify that the controller sends the same channel and CC numbers as \`profile.json\`, and that all Max parameters use the exact Long Names from the spec.
`

  return {
    scriptSlug,
    '__init__.py': initPy,
    [`${scriptSlug}.py`]: scriptPy,
    'profile.json': `${JSON.stringify(profile, null, 2)}\n`,
    'README.md': readme,
    'INSTALLATION.md': installation,
  }
}

export function generateM4LSpec(target) {
  const names = generateParameterNames(target)
  const buttonNames = generateButtonNames(target)
  return `# ${target.targetDeviceName} — ${target.parameterCount} Parameter Specification

The Max for Live device must be named **${target.targetDeviceName}**. Add exposed \`live.dial\` or \`live.toggle\` objects and set their **Long Name** exactly as follows:

${names.map((name, index) => `${index + 1}. \`${name}\``).join('\n')}

Add exposed \`live.toggle\` objects with these Long Names:

${buttonNames.map((name, index) => `${index + 1}. \`${name}\``).join('\n')}

## Contract

- Parameter names are matched exactly first, then with spaces and punctuation removed.
- Keep every mapped control visible to Live's parameter system.
- Parameter indices are optional fallbacks and are zero-based in the generated profile.
- Save the finished device as an \`.amxd\` and place it wherever your User Library expects Max for Live devices.
`
}
