const normalizeSlug = (value) => {
  const slug = value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
  const safeSlug = slug || 'M4L_Remote_Mapper'
  return /^\d/.test(safeSlug) ? `M4L_${safeSlug}` : safeSlug
}

const pyString = (value) => JSON.stringify(String(value))

export const createScriptSlug = (deviceName) => `${normalizeSlug(deviceName)}_Remote`

export function generateParameterNames({ parameterCount, parameterPrefix }) {
  return Array.from(
    { length: Math.max(1, Number(parameterCount) || 1) },
    (_, index) => `${parameterPrefix || 'M4L Param'} ${index + 1}`,
  )
}

function buildPythonMappings(mappings) {
  const rows = mappings.map((mapping) => {
    const source = mapping.source
    if (mapping.targetType === 'global_action') {
      return `        {"channel": ${source.frameworkChannel}, "cc": ${source.data1}, "type": "global_action", "action": ${pyString(mapping.actionName)}, "trigger": ${pyString(mapping.triggerMode)}}`
    }
    const parameterIndex = mapping.parameterIndex === '' || mapping.parameterIndex == null
      ? 'None'
      : Number(mapping.parameterIndex)
    return `        {"channel": ${source.frameworkChannel}, "cc": ${source.data1}, "type": "m4l_parameter", "device": ${pyString(mapping.targetDeviceName)}, "parameter": ${pyString(mapping.targetParameterName)}, "parameter_index": ${parameterIndex}}`
  })
  return rows.length ? `${rows.join(',\n')}\n` : ''
}

export function generateRemoteScriptFiles({ target, mappings, scriptSlug = createScriptSlug(target.targetDeviceName) }) {
  const profile = {
    schemaVersion: '0.1',
    scriptSlug,
    target,
    mappings: mappings.map((mapping) => ({
      source: mapping.source,
      targetType: mapping.targetType,
      ...(mapping.targetType === 'global_action'
        ? { actionName: mapping.actionName, triggerMode: mapping.triggerMode }
        : {
            targetDeviceName: mapping.targetDeviceName,
            targetParameterName: mapping.targetParameterName,
            parameterIndex: mapping.parameterIndex === '' ? null : mapping.parameterIndex,
          }),
    })),
  }

  const initPy = `from .${scriptSlug} import ${scriptSlug}\n\n\ndef create_instance(c_instance):\n    return ${scriptSlug}(c_instance)\n`

  const scriptPy = `# Generated by M4L Remote Mapper v0.1
from _Framework.ControlSurface import ControlSurface


class ${scriptSlug}(ControlSurface):
    MAPPINGS = [
${buildPythonMappings(mappings)}    ]

    def __init__(self, c_instance):
        super(${scriptSlug}, self).__init__(c_instance)
        with self.component_guard():
            self._log("M4L Remote Mapper: loaded")
            self._setup_mappings()

    def _log(self, message):
        try:
            self.canonical_parent.log_message(message)
        except Exception:
            try:
                self.show_message(message)
            except Exception:
                pass

    def _setup_mappings(self):
        self._mappings = list(self.MAPPINGS)

    def receive_midi(self, midi_bytes):
        if len(midi_bytes) < 3:
            return
        status, data1, data2 = midi_bytes[0], midi_bytes[1], midi_bytes[2]
        if status & 0xF0 != 0xB0:
            return
        channel = status & 0x0F
        for mapping in self._mappings:
            if mapping["channel"] == channel and mapping["cc"] == data1:
                self._apply_mapping(mapping, data2)

    def _apply_mapping(self, mapping, value):
        if mapping["type"] == "global_action":
            self._run_global_action(mapping, value)
            return
        parameter = self._find_parameter(mapping)
        if parameter is None:
            self._log("M4L Remote Mapper: parameter not found: %s" % mapping["parameter"])
            return
        normalized_input = float(value) / 127.0
        normalized_value = parameter.min + normalized_input * (parameter.max - parameter.min)
        parameter.value = normalized_value

    def _run_global_action(self, mapping, value):
        should_trigger = (
            mapping["trigger"] == "value_gt_0" and value > 0
        ) or (
            mapping["trigger"] == "value_eq_127" and value == 127
        )
        if not should_trigger or mapping["action"] != "Capture MIDI":
            return
        self._log("M4L Remote Mapper: global action requested: Capture MIDI")
        try:
            self.song().capture_midi()
            self._log("M4L Remote Mapper: capture_midi success")
        except Exception as error:
            self._log("M4L Remote Mapper: capture_midi error: %s" % error)

    def _find_parameter(self, mapping):
        target_device = None
        for track in list(self.song().tracks) + list(self.song().return_tracks):
            target_device = self._find_device_in_chain(track.devices, mapping["device"])
            if target_device is not None:
                break
        if target_device is None:
            return None

        exact_name = mapping["parameter"]
        for parameter in target_device.parameters:
            if parameter.name == exact_name:
                return parameter

        normalized_name = self._normalize_name(exact_name)
        for parameter in target_device.parameters:
            if self._normalize_name(parameter.name) == normalized_name:
                return parameter

        index = mapping.get("parameter_index")
        if index is not None and 0 <= index < len(target_device.parameters):
            return target_device.parameters[index]
        return None

    def _find_device_in_chain(self, devices, target_name):
        normalized_target = self._normalize_name(target_name)
        for device in devices:
            if device.name == target_name or self._normalize_name(device.name) == normalized_target:
                return device
            if getattr(device, "can_have_chains", False):
                for chain in device.chains:
                    nested = self._find_device_in_chain(chain.devices, target_name)
                    if nested is not None:
                        return nested
        return None

    @staticmethod
    def _normalize_name(value):
        return "".join(character.lower() for character in value if character.isalnum())
`

  const readme = `# ${target.targetDeviceName} Remote Pack

Generated by M4L Remote Mapper. This pack connects MIDI CC messages to named Max for Live parameters and Ableton global actions.

## Profile

- Target device: **${target.targetDeviceName}**
- Parameters: **${target.parameterCount}**
- Active mappings: **${mappings.length}**
- Remote Script folder: \`${scriptSlug}\`

See \`INSTALLATION.md\` for setup instructions and \`Max for Live/README.md\` for the device contract.
`

  const installation = `# Installation

1. Quit Ableton Live.
2. Copy \`Remote Scripts/${scriptSlug}\` into Ableton's User Remote Scripts folder.
   - macOS: \`~/Music/Ableton/User Library/Remote Scripts/\`
   - Windows: \`%USERPROFILE%\\Documents\\Ableton\\User Library\\Remote Scripts\\\`
3. Build or open your Max for Live device using the specification in \`Max for Live/\`.
4. Restart Live and open **Settings → Link, Tempo & MIDI**.
5. Select **${scriptSlug}** in a Control Surface slot and choose the mapped controller as MIDI Input.
6. Add the Max for Live device named **${target.targetDeviceName}** to a track.
7. Move a mapped control and verify the parameter response.

If nothing moves, verify that the controller sends the same channel and CC numbers as \`profile.json\`, and that all Max parameters use the exact Long Names from the spec.
`

  return {
    scriptSlug,
    '__init__.py': initPy,
    [`${scriptSlug}.py`]: scriptPy,
    'profile.json': `${JSON.stringify(profile, null, 2)}\n`,
    'README.md': readme,
    'INSTALLATION.md': installation,
  }
}

export function generateM4LSpec(target) {
  const names = generateParameterNames(target)
  return `# ${target.targetDeviceName} — ${target.parameterCount} Parameter Specification

The Max for Live device must be named **${target.targetDeviceName}**. Add exposed \`live.dial\` or \`live.toggle\` objects and set their **Long Name** exactly as follows:

${names.map((name, index) => `${index + 1}. \`${name}\``).join('\n')}

## Contract

- Parameter names are matched exactly first, then with spaces and punctuation removed.
- Keep every mapped control visible to Live's parameter system.
- Parameter indices are optional fallbacks and are zero-based in the generated profile.
- Save the finished device as an \`.amxd\` and place it wherever your User Library expects Max for Live devices.
`
}
